version: "3.8"

name: board
services:
  app: # docker compose -f --profile app-docker up --build
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: board-app
    profiles: [ "app-docker" ]
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mysql:
    image: mysql:8.4.7
    container_name: board-test-mysql
    ports:
      - "3306:3306"
    volumes:
      # 데이터 영속성 필요시 주석 해제 - mysql_data:/var/lib/mysql
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: board_test
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:7.4-alpine
    container_name: board-test-redis
    ports:
      - "6379:6379"
    # restart: always
  k6: # docker compose --profile loadtest run --rm k6
    image: grafana/k6:latest
    container_name: board-k6
    profiles: ["loadtest"]
    volumes:
      - ../k6:/scripts
    working_dir: /scripts
    command: run /scripts/hot-key.js
    environment:
      BASE_URL: http://host.docker.internal:8080
      ARTICLE_NO: "1"
      PATH_TEMPLATE: /articles/{articleNo}