CREATE TABLE IF NOT EXISTS article (
    article_no BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    view_count BIGINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_no)
) ENGINE=InnoDB;